# Generated by Django 4.0 on 2022-01-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_extrainformation_landinformation_customuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landinformation',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
