# Generated by Django 4.0 on 2022-01-12 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sellerlands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.extrainformation'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.extrainformation'),
        ),
    ]
