# Generated by Django 4.0 on 2022-01-12 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_buyer_info_alter_seller_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.extrainformation'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.extrainformation'),
        ),
    ]
