# Generated by Django 4.0 on 2022-01-12 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_buyer_info_alter_seller_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.extrainformation'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.extrainformation'),
        ),
    ]
