# Generated by Django 4.0 on 2022-01-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_buyer_info_alter_seller_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='landinformation',
            name='land_paper_images_first',
            field=models.ImageField(default='_', upload_to='papers/'),
        ),
        migrations.AddField(
            model_name='landinformation',
            name='land_paper_images_second',
            field=models.ImageField(default='_', upload_to='papers/'),
        ),
        migrations.AddField(
            model_name='landinformation',
            name='land_paper_images_third',
            field=models.ImageField(default='_', upload_to='papers/'),
        ),
    ]
